apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-upgrade-role
  namespace: app
rules:
  - apiGroups: ['apps', '']
    resources: ['deployments', 'services']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'delete']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-upgrade-rolebinding
  namespace: app
subjects:
  - kind: ServiceAccount
    name: jenkins-service-account
    namespace: default
roleRef:
  kind: Role
  name: helm-upgrade-role
  apiGroup: rbac.authorization.k8s.io
