apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-custom-config
data:
  my.cnf: |
    [mysqld]
    host-cache-size=0
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql

    pid-file=/var/run/mysqld/mysqld.pid
    [client]
    default-character-set=utf8
    socket=/var/run/mysqld/mysqld.sock

    [mysql]
    default-character-set=utf8